<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-08-17">
<meta name="keywords" content="nfl analytics, field goals, selection bias, inverse probability weighting, mixed effects models">

<title>Here’s the Kicker: Correcting Selection Bias in NFL Field Goal Models via Inverse Probability Weighting</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-67270d1595a62d14f123c043d4fb2f18.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script async="" src="https://hypothes.is/embed.js"></script>
<script>
  window.document.addEventListener("DOMContentLoaded", function (_event) {
    document.body.classList.add('hypothesis-enabled');
  });
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta name="citation_title" content="Here&amp;amp;#039;s the Kicker: Correcting Selection Bias in NFL Field Goal Models via Inverse Probability Weighting">
<meta name="citation_keywords" content="nfl analytics,field goals,selection bias,inverse probability weighting,mixed effects models">
<meta name="citation_author" content="Elliott Kervin">
<meta name="citation_author" content="Dr. Michael Schuckers">
<meta name="citation_publication_date" content="2026-08-17">
<meta name="citation_cover_date" content="2026-08-17">
<meta name="citation_year" content="2026">
<meta name="citation_online_date" content="2026-08-17">
<meta name="citation_language" content="en">
<meta name="citation_reference" content="citation_title=nflfastR: Functions to efficiently access NFL play by play data;,citation_author=Sebastian Carl;,citation_author=Ben Baldwin;,citation_publication_date=2026;,citation_cover_date=2026;,citation_year=2026;,citation_fulltext_html_url=https://nflfastr.com/;">
<meta name="citation_reference" content="citation_title=Shrinkage estimation of NFL field goal success probabilities;,citation_author=Jason A. Osborne;,citation_author=Richard A. Levine;,citation_publication_date=2017;,citation_cover_date=2017;,citation_year=2017;,citation_issue=2;,citation_doi=10.3233/JSA-16140;,citation_volume=3;,citation_journal_title=Journal of Sports Analytics;">
<meta name="citation_reference" content="citation_title=An expectation-based metric for NFL field goal kickers;,citation_author=R. Drew Pasteur;,citation_author=Kyle Cunningham-Rhoads;,citation_publication_date=2014;,citation_cover_date=2014;,citation_year=2014;,citation_issue=1;,citation_doi=10.1515/jqas-2013-0039;,citation_volume=10;,citation_journal_title=Journal of Quantitative Analysis in Sports;">
<meta name="citation_reference" content="citation_title=A better way to evaluate NFL kickers;,citation_author=Jacob A. Long;,citation_publication_date=2019;,citation_cover_date=2019;,citation_year=2019;,citation_publisher=https://jacob-long.com/post/evaluating-kickers/;">
<meta name="citation_reference" content="citation_title=Building a statistical model for field goal kicker accuracy;,citation_author=Jacob A. Long;,citation_publication_date=2019;,citation_cover_date=2019;,citation_year=2019;,citation_publisher=https://jacob-long.com/post/kickers-methods-notes/;">
</head>

<body class="quarto-light">

<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Here’s the Kicker: Correcting Selection Bias in NFL Field Goal Models via Inverse Probability Weighting</h1>
          </div>

    
    <div class="quarto-title-meta-container">
      <div class="quarto-title-meta-column-start">
            <div class="quarto-title-meta-author">
          <div class="quarto-title-meta-heading">Authors</div>
          <div class="quarto-title-meta-heading">Affiliation</div>
          
                <div class="quarto-title-meta-contents">
            <p class="author">Elliott Kervin </p>
          </div>
                <div class="quarto-title-meta-contents">
                    <p class="affiliation">
                        The University of North Carolina at Charlotte
                      </p>
                  </div>
                      <div class="quarto-title-meta-contents">
            <p class="author">Dr.&nbsp;Michael Schuckers </p>
          </div>
                <div class="quarto-title-meta-contents">
                    <p class="affiliation">
                        The University of North Carolina at Charlotte
                      </p>
                  </div>
                    </div>
        
        <div class="quarto-title-meta">

                      
                <div>
            <div class="quarto-title-meta-heading">Published</div>
            <div class="quarto-title-meta-contents">
              <p class="date">August 17, 2026</p>
            </div>
          </div>
          
                
              </div>
      </div>
      <div class="quarto-title-meta-column-end quarto-other-formats-target">
      <div class="quarto-alternate-formats"><div class="quarto-title-meta-heading">Other Formats</div><div class="quarto-title-meta-contents"><p><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></p></div><div class="quarto-title-meta-contents"><p><a href="index.pdf"><i class="bi bi-file-pdf"></i>PDF</a></p></div><div class="quarto-title-meta-contents"><p><a href="index-meca.zip" data-meca-link="true"><i class="bi bi-archive"></i>MECA Bundle</a></p></div></div></div>
    </div>


    <div>
      <div class="keywords">
        <div class="block-title">Keywords</div>
        <p>nfl analytics, field goals, selection bias, inverse probability weighting, mixed effects models</p>
      </div>
    </div>

    <div class="quarto-other-links-text-target">
    </div>  </div>
</header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract">Abstract</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">1. Introduction</a>
  <ul class="collapse">
  <li><a href="#motivation" id="toc-motivation" class="nav-link" data-scroll-target="#motivation">1.1 Motivation</a></li>
  <li><a href="#research-questions" id="toc-research-questions" class="nav-link" data-scroll-target="#research-questions">1.2 Research Questions</a></li>
  </ul></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">2. Data</a>
  <ul class="collapse">
  <li><a href="#data-universe" id="toc-data-universe" class="nav-link" data-scroll-target="#data-universe">2.1 Data Universe</a></li>
  <li><a href="#feature-engineering" id="toc-feature-engineering" class="nav-link" data-scroll-target="#feature-engineering">2.2 Feature Engineering</a></li>
  <li><a href="#weighting-method" id="toc-weighting-method" class="nav-link" data-scroll-target="#weighting-method">2.3 Weighting Method</a></li>
  </ul></li>
  <li><a href="#attempt-propensity-model" id="toc-attempt-propensity-model" class="nav-link" data-scroll-target="#attempt-propensity-model">3. Attempt Propensity Model</a>
  <ul class="collapse">
  <li><a href="#decision-framework" id="toc-decision-framework" class="nav-link" data-scroll-target="#decision-framework">3.1 Decision Framework</a></li>
  <li><a href="#model-specification" id="toc-model-specification" class="nav-link" data-scroll-target="#model-specification">3.2 Model Specification</a></li>
  <li><a href="#training-protocol" id="toc-training-protocol" class="nav-link" data-scroll-target="#training-protocol">3.3 Training Protocol</a></li>
  <li><a href="#propensity-model-results" id="toc-propensity-model-results" class="nav-link" data-scroll-target="#propensity-model-results">3.4 Propensity Model Results</a></li>
  </ul></li>
  <li><a href="#models-and-methods" id="toc-models-and-methods" class="nav-link" data-scroll-target="#models-and-methods">4. Models and Methods</a>
  <ul class="collapse">
  <li><a href="#success-models" id="toc-success-models" class="nav-link" data-scroll-target="#success-models">4.1 Success Models</a></li>
  <li><a href="#evaluation-metrics" id="toc-evaluation-metrics" class="nav-link" data-scroll-target="#evaluation-metrics">4.2 Evaluation Metrics</a></li>
  <li><a href="#inference-and-robustness-policy" id="toc-inference-and-robustness-policy" class="nav-link" data-scroll-target="#inference-and-robustness-policy">4.3 Inference and Robustness Policy</a></li>
  </ul></li>
  <li><a href="#modeling-results" id="toc-modeling-results" class="nav-link" data-scroll-target="#modeling-results">5. Modeling Results</a>
  <ul class="collapse">
  <li><a href="#predictive-benchmark-across-models" id="toc-predictive-benchmark-across-models" class="nav-link" data-scroll-target="#predictive-benchmark-across-models">5.1 Predictive Benchmark Across Models</a></li>
  <li><a href="#m2-augmentation-with-pseudo-labels" id="toc-m2-augmentation-with-pseudo-labels" class="nav-link" data-scroll-target="#m2-augmentation-with-pseudo-labels">5.2 M2: Augmentation with Pseudo-Labels</a></li>
  <li><a href="#m3-inverse-probability-weighting-and-the-distance-tail" id="toc-m3-inverse-probability-weighting-and-the-distance-tail" class="nav-link" data-scroll-target="#m3-inverse-probability-weighting-and-the-distance-tail">5.3 M3: Inverse Probability Weighting and the Distance Tail</a></li>
  <li><a href="#era-stability-of-the-selection-bias-result" id="toc-era-stability-of-the-selection-bias-result" class="nav-link" data-scroll-target="#era-stability-of-the-selection-bias-result">5.4 Era Stability of the Selection-Bias Result</a></li>
  </ul></li>
  <li><a href="#fgoe-and-player-evaluations" id="toc-fgoe-and-player-evaluations" class="nav-link" data-scroll-target="#fgoe-and-player-evaluations">6. FGOE and Player Evaluations</a></li>
  <li><a href="#field-goal-kicking-trends" id="toc-field-goal-kicking-trends" class="nav-link" data-scroll-target="#field-goal-kicking-trends">7. Field Goal Kicking Trends</a>
  <ul class="collapse">
  <li><a href="#decision-evolution-by-yardage-context" id="toc-decision-evolution-by-yardage-context" class="nav-link" data-scroll-target="#decision-evolution-by-yardage-context">7.1 Decision Evolution by Yardage Context</a></li>
  <li><a href="#win-probability-added-and-the-decision-framework" id="toc-win-probability-added-and-the-decision-framework" class="nav-link" data-scroll-target="#win-probability-added-and-the-decision-framework">7.2 Win Probability Added and the Decision Framework</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">8. Discussion</a>
  <ul class="collapse">
  <li><a href="#why-corrective-models-do-not-win-out-of-sample-prediction" id="toc-why-corrective-models-do-not-win-out-of-sample-prediction" class="nav-link" data-scroll-target="#why-corrective-models-do-not-win-out-of-sample-prediction">8.1 Why Corrective Models Do Not Win Out-of-Sample Prediction</a></li>
  <li><a href="#operational-implications" id="toc-operational-implications" class="nav-link" data-scroll-target="#operational-implications">8.2 Operational Implications</a></li>
  </ul></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations">9. Limitations</a>
  <ul class="collapse">
  <li><a href="#estimand-and-the-relationship-to-causal-inference" id="toc-estimand-and-the-relationship-to-causal-inference" class="nav-link" data-scroll-target="#estimand-and-the-relationship-to-causal-inference">9.1 Estimand and the Relationship to Causal Inference</a></li>
  <li><a href="#other-limitations" id="toc-other-limitations" class="nav-link" data-scroll-target="#other-limitations">9.2 Other Limitations</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">10. Conclusion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content quarto-banner-title-block" id="quarto-document-content">



  


<section id="abstract" class="level1">
<h1>Abstract</h1>
<p>NFL field goal (FG) outcomes are observed under a selective coaching decision process. We assert that teams attempt kicks in favorable game states, so the observed attempt distribution over-represents an easier subset of the full universe of possible kicks. We compare the results of an unweighted full generalized linear mixed model (GLMM) baseline (M1) to two successive attempts at correcting that selection. The first builds a more complete training universe directly, augmenting the observed attempts with point-after-touchdown (PAT) kicks and with declined fourth-down attempts entered as assumed misses (M2). The second applies inverse probability weighting (IPW) to reweight observed FG attempts by the inverse of their estimated propensity to be attempted (M3). The attempt propensity model is trained on a rolling window of all fourth-down plays (<span class="math inline">\(n = 32,666\)</span> plays) to predict coaching decisions. The success outcome models are trained and evaluated on actual FG attempts (<span class="math inline">\(n = 11,548\)</span> in-sample attempts; <span class="math inline">\(n = 2,251\)</span> held-out test kicks). M2 does not improve on M1 on either split, and heavier augmentation weights degrade its fit further rather than sharpening it. M3 fares better in-sample, achieving the best fit overall (Brier 0.0982, log-loss 0.3216) with calibration gains concentrated at long distances: a 22.1% Brier reduction at 60+ yards and a 5.6% reduction at 50-59 yards versus M1. Out of sample, however, M1 outperforms M3 (Brier 0.1004 vs.&nbsp;0.1026; log-loss 0.3295 vs.&nbsp;0.3367). The out-of-sample ordering is the same in the pre-2020 and post-2020 halves of the sample. The in-sample improvements are primarily driven by error reduction on the upweighted longer kicks, though these gains do not generalize to out-of-sample data. In predictive terms, correcting for coaching selection does not improve held-out forecasts of kick success. Out-of-sample accuracy remains almost entirely a function of distance and environmental covariates. This is a statement about predictive performance, not about the causal effect of the attempt decision. We recommend M1 as the predictive benchmark, and introduce field goals over expectation (FGOE), derived from a population-marginal variant of M3, as a principled kicker evaluation metric.</p>
</section>
<section id="introduction" class="level1">
<h1>1. Introduction</h1>
<section id="motivation" class="level2">
<h2 class="anchored" data-anchor-id="motivation">1.1 Motivation</h2>
<p>NFL field goal kicking is a high-stakes, discrete skill evaluated routinely by teams, broadcasters, and analysts. Kicker performance metrics typically compare observed make rates or expected points added to league-average baselines derived from models trained on attempted kicks. Prior work has attempted to address these difficulties using expectation-based metrics <span class="citation" data-cites="pasteur2014 osborne2017">(<a href="#ref-pasteur2014" role="doc-biblioref">Pasteur and Cunningham-Rhoads 2014</a>; <a href="#ref-osborne2017" role="doc-biblioref">Osborne and Levine 2017</a>)</span> and distance-adjusted baselines <span class="citation" data-cites="long2019eval long2019methods">(<a href="#ref-long2019eval" role="doc-biblioref">Long 2019a</a>, <a href="#ref-long2019methods" role="doc-biblioref">2019b</a>)</span>, but nearly all such metrics share a structural limitation: they condition on attempts that coaches chose to take.</p>
<p>Coaching selection is not random. When a team faces fourth down at the opponent’s 35-yard line, leading or trailing by a few points, the decision to attempt a field goal reflects the coach’s assessment of kick distance, weather, the kicker’s perceived range, score context, and game leverage. In more favorable situations, kicks are more likely to be attempted. As a result, the observed distribution of FG attempts may systematically over-represent favorable situations and under-represent long, difficult, or weather-degraded attempts.</p>
<p>This motivates a hypothesis that the remainder of the paper tests. If the selection process is sufficiently structured, models trained exclusively on observed attempts may inherit that structure, and kicker evaluation metrics built on them may not fully account for the difficulty distribution each kicker faces. The assumed mechanism is that coaches who trust their kicker’s ability assign more difficult kicks, meaning longer attempts, kicks in severe weather, or attempts in high-pressure game states. This is a conjecture about the data-generating process rather than a quantity we estimate, and nothing in what follows should be read as evidence that coaches behave this way. Our corrections for the selection bias aim to capture the information inherent in a coach’s decision to kick, when punting or going for it would have been reasonable, or even probable, alternatives. Should the effect be meaningful, raw make rates or simple distance-based baselines would penalize trusted players by ignoring the selective difficulty of their attempts.</p>
<p>This paper investigates whether correcting for coaching selection bias through inverse probability weighting improves field goal outcome models, and whether such corrections produce fairer kicker evaluation metrics. We test whether the selection mechanism is strong enough to warrant a propensity-based correction, and whether the resulting adjustments translate into predictive gains.</p>
</section>
<section id="research-questions" class="level2">
<h2 class="anchored" data-anchor-id="research-questions">1.2 Research Questions</h2>
<p>Three research questions guide this analysis:</p>
<ol type="1">
<li>Are coaching decisions concerning field goal attempts sufficiently structured to support a propensity-based correction? Specifically, can a multinomial model trained on game-state features predict whether a team will kick with high accuracy?</li>
<li>Does augmenting the outcome model training set with non-attempt pseudo-labels (assumed misses) improve long-distance calibration and, if so, at what predictive cost?</li>
<li>Does Inverse Probability Weighting (IPW) of observed FG attempts, based on attempt likelihood, improve out-of-sample predictive accuracy relative to an unweighted full GLMM baseline?</li>
</ol>
</section>
</section>
<section id="data" class="level1">
<h1>2. Data</h1>
<section id="data-universe" class="level2">
<h2 class="anchored" data-anchor-id="data-universe">2.1 Data Universe</h2>
<p>Play-by-play data were obtained via the nflfastR R package <span class="citation" data-cites="nflfastr">(<a href="#ref-nflfastr" role="doc-biblioref">Carl and Baldwin 2026</a>)</span> covering the 2015-2025 NFL regular and post-seasons. The in-sample training set comprised 11,548 FG attempts. Blocked kicks were explicitly excluded from both training and evaluation, as they represent a team-level defensive protection outcome rather than individual kicker success or skill.</p>
<p>The same fourth-down filtering logic supplies the non-attempt situations used both to train the propensity model and to augment M2. Out of 78,563 raw fourth-down situations, filtering for field position within plausible kicking range (kick distance <span class="math inline">\(\leq\)</span> 70 yards) leaves 32,666 plays. An additional 14,073 point-after-touchdown (PAT) attempts were used for M2 data augmentation.</p>
<p>A 20% stratified random sample of games (593 games) formed the held-out test set (<span class="math inline">\(n = 2,251\)</span> kicks). This test set contains only actual field goal attempts (not fourth-down non-attempts or PATs) drawn from disjoint games which otherwise maintain player and season overlaps with the training set (<span class="math inline">\(n = 9,297\)</span> training attempts). The analysis spans 11 seasons (2015-2025), covering the modern NFL kicking environment following rule changes that shifted PAT distance.</p>
<p>Because the split is drawn at the game level, the held-out kicks are clustered rather than independently sampled, and it is worth checking directly that the test set is not an unusual draw with respect to the attempt distribution. <a href="#tbl-split-balance" class="quarto-xref">Table&nbsp;1</a> reports the comparison. The two halves are closely matched as mean kick distance differs by only 0.32 yards and the largest distance-band share gap is 1.33 percentage points, while the mean estimated attempt propensity differs by 0.006. To assess whether the residual imbalance is larger than chance, we re-drew the held-out games 2,000 times under the same season-stratified design and recomputed the total variation distance between the two band distributions. The observed value (0.0133) sits <em>below</em> the median of that null distribution (0.0164), giving a permutation <span class="math inline">\(p\)</span>-value of 0.68. The realized split is therefore an unremarkable draw, and Section 8.1 relies on this when interpreting M3’s out-of-sample result.</p>
<div id="tbl-split-balance" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-split-balance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Balance of the attempt distribution between the training games and the held-out games. Distance bands follow the convention used in <a href="#tbl-dist-brier" class="quarto-xref">Table&nbsp;5</a>. Season-stratified game-level permutation test on the band shares: observed total variation distance 0.0133, null median 0.0164, <span class="math inline">\(p = 0.68\)</span> over 2,000 redraws.
</figcaption>
<div aria-describedby="tbl-split-balance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Distance Band</th>
<th style="text-align: right;">Train n</th>
<th style="text-align: right;">Train share</th>
<th style="text-align: right;">Test n</th>
<th style="text-align: right;">Test share</th>
<th style="text-align: right;">Difference (pp)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>&lt; 30 yds</td>
<td style="text-align: right;">2,453</td>
<td style="text-align: right;">26.4%</td>
<td style="text-align: right;">564</td>
<td style="text-align: right;">25.1%</td>
<td style="text-align: right;">-1.33</td>
</tr>
<tr class="even">
<td>30-39 yds</td>
<td style="text-align: right;">2,664</td>
<td style="text-align: right;">28.7%</td>
<td style="text-align: right;">650</td>
<td style="text-align: right;">28.9%</td>
<td style="text-align: right;">+0.22</td>
</tr>
<tr class="odd">
<td>40-49 yds</td>
<td style="text-align: right;">2,726</td>
<td style="text-align: right;">29.3%</td>
<td style="text-align: right;">681</td>
<td style="text-align: right;">30.3%</td>
<td style="text-align: right;">+0.93</td>
</tr>
<tr class="even">
<td>50-59 yds</td>
<td style="text-align: right;">1,392</td>
<td style="text-align: right;">15.0%</td>
<td style="text-align: right;">341</td>
<td style="text-align: right;">15.1%</td>
<td style="text-align: right;">+0.18</td>
</tr>
<tr class="odd">
<td>60+ yds</td>
<td style="text-align: right;">62</td>
<td style="text-align: right;">0.7%</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">0.7%</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="even">
<td><strong>Mean kick distance</strong></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">38.68</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">39.00</td>
<td style="text-align: right;">+0.32 yds</td>
</tr>
<tr class="odd">
<td><strong>Mean <span class="math inline">\(\hat{\pi}(X)\)</span></strong></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">0.827</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">0.821</td>
<td style="text-align: right;">-0.006</td>
</tr>
<tr class="even">
<td><strong>Mean IPW weight</strong></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">0.957</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">0.977</td>
<td style="text-align: right;">+0.020</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="feature-engineering" class="level2">
<h2 class="anchored" data-anchor-id="feature-engineering">2.2 Feature Engineering</h2>
<p>The primary distance covariate was encoded as a seven-column cubic B-spline basis using <code>bSpline()</code> from the splines2 R package. Interior knots were placed at 28, 38, 48, and 58 yards; boundary knots at 18 and 70 yards; the intercept column was excluded from the spline basis, yielding seven identifiable basis vectors spanning the relevant distance range.</p>
<p>Wind speed (mph), temperature (<span class="math inline">\(^\circ\)</span>F), and relative humidity (%) were standardized to z-scores globally across the entire attempted kick set to capture standard environmental difficulty. Humidity is parsed from the same game-level weather string as temperature and wind, with indoor games assigned a fixed climate-controlled value and remaining gaps imputed by stadium-month median. Surface type (turf vs.&nbsp;grass), precipitation category (rain showers, snow/sleet), game-clock context (clock running, within last two minutes of a half), iced kicker indicator, and playoff indicator were included as binary covariates.</p>
<p>The weather fields are parsed from free-text game weather strings, and the wind field in particular contained a small number of values that were determined to be errors rather than real readings, most notably 71 mph in a 2016 game and 70 mph in a 2008 game. We corrected values that fell outside a plausibility threshold of 40 mph. The correction is applied during data preparation, before any downstream standardization or model fitting. Affected rows are treated as missing and re-imputed with the median wind among outdoor attempted kicks below the threshold (8 mph) rather than clipped to the threshold itself. This affects 58 of 137,668 rows across 3 distinct games (0.04%), comprising 7 field goal attempts, 14 PATs, and 37 fourth-down non-attempts. Temperature and humidity showed no comparable outliers and are not corrected.</p>
<p><a href="#fig-weather-raw" class="quarto-xref">Figure&nbsp;1</a> shows the unadjusted relationships in the raw data. The marginal effects are modest in all three variables, and none is dramatically non-linear over the range where the data are dense. Make rate declines gently and close to monotonically with humidity and temperature is close to flat across its central range. Wind is the least monotone of the three, sitting near 87-88% in near windless conditions, where the vast majority of observations are concentrated. This falls to roughly 84.5% by 10-12 mph, and then turns modestly upward, although that upturn rests on few kicks and carries wide intervals. The binned points and the LOESS agree closely in all three panels. These panels are not adjusted for distance and therefore establish the shape of the marginal relationships rather than the size of any weather effect.</p>
<div id="fig-weather-raw" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-weather-raw-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../../reports/figures/weather_make_rate_raw.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;1: Raw make rate versus each weather covariate, unadjusted for kick distance."><img src="../../reports/figures/weather_make_rate_raw.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-weather-raw-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Raw make rate versus each weather covariate, unadjusted for kick distance.
</figcaption>
</figure>
</div>
<p><a href="#fig-weather-band" class="quarto-xref">Figure&nbsp;2</a> repeats the exercise within a fixed 40-54 yard band, where the distance mix is roughly held constant.</p>
<div id="fig-weather-band" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-weather-band-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../../reports/figures/weather_make_rate_40_54.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figure&nbsp;2: Raw make rate versus each weather covariate within a fixed 40-54 yard distance band."><img src="../../reports/figures/weather_make_rate_40_54.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-weather-band-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Raw make rate versus each weather covariate within a fixed 40-54 yard distance band.
</figcaption>
</figure>
</div>
<p>The three continuous weather covariates enter the outcome model as natural cubic spline main effects with three degrees of freedom each rather than as linear terms. The spline bases are constructed once from the distribution of attempted kicks and then applied unchanged to every row used anywhere in the analysis, so that field goals, PATs, non-attempts, and all held-out prediction sets are mapped through an identical basis.</p>
<p>Stadium-level effects (dome, climate, altitude) were modeled with a stadium random intercept. Kicker ability and season-to-season variation were captured with a nested kicker-season random intercept.</p>
</section>
<section id="weighting-method" class="level2">
<h2 class="anchored" data-anchor-id="weighting-method">2.3 Weighting Method</h2>
<p>Stabilized inverse probability weights (IPW) were computed for each attempted kick play:</p>
<p><span class="math display">\[w_i^{\text{raw}} = \frac{\bar{\pi}}{\hat{\pi}(X_i)}\]</span></p>
<p>where <span class="math inline">\(\bar{\pi}\)</span> is the marginal FG attempt prevalence over all plays, and <span class="math inline">\(\hat{\pi}(X_i)\)</span> is the clipped propensity score.</p>
<p>The weight-building process has three stages:</p>
<ol type="1">
<li><strong>Clipped propensity</strong>: Model-dervied propensity scores are clipped to the <span class="math inline">\([0.02, 0.98]\)</span> interval to avoid division issues, and stabilized IPW case weights are computed from the clipped scores.</li>
<li><strong>Normalize <span class="math inline">\(\rightarrow\)</span> cap <span class="math inline">\(\rightarrow\)</span> renormalize</strong>: The raw weights are Hajek-normalized to mean one within each season, capped at three standard deviations above the seasonal mean (<span class="math inline">\(\bar{w}_s + 3\sigma_{w,s}\)</span>), and then renormalized per season. The two normalizations are not redundant. The cap is defined relative to the seasonal mean and standard deviation, so the first normalization puts every season on a common scale before the cap is applied, and the second restores the per-season mean of exactly 1.0 that the cap necessarily perturbs by truncating the upper tail.</li>
<li><strong>Result</strong>: A per-kick case weight with mean 1.0 in every season and a bounded upper tail.</li>
</ol>
<p>The resulting case weight, <code>weight_multinom_hajek</code>, concentrates weight on long-range, weather-degraded, or contextually unfavorable attempts that coaches selectively avoid, correcting the under-representation of those conditions in the raw sample. As shown in <a href="#fig-weights" class="quarto-xref">Figure&nbsp;3</a>, kick distance is the primary determinant of weight magnitude, with longer kicks receiving larger weights because they are less likely to be attempted. Environmental factors (wind, temperature) and game-state context introduce further variance around this distance trend. The propensity model used to estimate these attempt probabilities is described in the following section.</p>
<div id="fig-weights" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-weights-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../../reports/figures/weights_vs_distance.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Figure&nbsp;3: Stabilized IPW case weight versus kick distance for attempted field goals."><img src="../../reports/figures/weights_vs_distance.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-weights-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Stabilized IPW case weight versus kick distance for attempted field goals.
</figcaption>
</figure>
</div>
</section>
</section>
<section id="attempt-propensity-model" class="level1">
<h1>3. Attempt Propensity Model</h1>
<section id="decision-framework" class="level2">
<h2 class="anchored" data-anchor-id="decision-framework">3.1 Decision Framework</h2>
<p>The coaching choice on fourth down represents a three-option decision landscape: attempt a field goal, punt, or “go for it” (defined as choosing to run a pass or rush play on fourth down). Formally, let <span class="math inline">\(D_i \in \{\text{FG}, \text{Punt}, \text{Go}\}\)</span> denote the coaching decision on play <span class="math inline">\(i\)</span>. The attempt propensity model estimates the conditional probability of each decision given the game-state feature vector <span class="math inline">\(X_i\)</span>:</p>
<p><span class="math display">\[P(D_i = d \mid X_i), \quad d \in \{\text{FG}, \text{Punt}, \text{Go}\}\]</span></p>
<p>The quantity of interest for the IPW framework is <span class="math inline">\(\hat{\pi}(X_i) = P(D_i = \text{FG} \mid X_i)\)</span>, the estimated probability that a field goal is attempted. Because coaches weigh the win-probability consequences of the kick when making this choice, <span class="math inline">\(X_i\)</span> includes a win-probability-based leverage term in addition to field position, clock, and score state. Its construction, and our reasons for building it rather than adopting an existing win probability model, are described in Section 3.2.</p>
</section>
<section id="model-specification" class="level2">
<h2 class="anchored" data-anchor-id="model-specification">3.2 Model Specification</h2>
<p>A multinomial logistic regression was fitted using the <code>nnet::multinom</code> function in R, with “go for it” as the reference category. The model predicts the log-odds of each non-reference category (FG, Punt) relative to “go for it.”</p>
<p>The feature set includes:</p>
<ul>
<li><strong>Field position</strong>: A cubic B-spline basis on the hypothetical kick distance the situation would produce, using the same knot placement as the outcome model (Section 2.2).</li>
<li><strong>Time remaining</strong>: A natural cubic spline on <code>game_seconds_remaining</code> with 4 degrees of freedom, capturing the nonlinear effect of game clock on coaching urgency.</li>
<li><strong>Quarter-time interactions</strong>: Log-transformed quarter seconds remaining interacted with second-quarter and fourth-quarter indicator flags, capturing the heightened time sensitivity in end-of-half and end-of-game situations.</li>
<li><strong>Yards to achieve first down</strong>: <code>ydstogo</code>, reflecting the conversion difficulty that drives the go-for-it vs.&nbsp;kick tradeoff.</li>
<li><strong>Score state</strong>: Binary indicators for game-state categories, including go-ahead (within 2 points), to-tie (down by 3), one-score-down (down 4-8), extend-lead (ahead by 1+), and two-score-down (down 9-11).</li>
<li><strong>Venue and weather</strong>: Indicators for indoor stadium, turf surface, and high altitude.</li>
<li><strong>Game leverage</strong>: A standardized leverage metric (<code>leverage_z</code>); see the discussion below.</li>
<li><strong>Wind and temperature</strong>: Standardized z-scores for wind speed and temperature.</li>
</ul>
<p>A field goal’s win-probability impact is available in the nflfastR data but depends on whether the kick is made or missed. A coach must decide whether to attempt it <em>before</em> that outcome is known. <code>leverage_z</code> resolves this by estimating, for each fourth-down situation, the win probability the kicking team would hold immediately after a make and immediately after a miss, and taking the difference. This represents the cost-benefit analysis a coach must weigh when making kick decisions in-game. Our estimates come from fractional-logit models fit to observed win-probability changes, with rule-based overrides at the endgame tails (e.g., a kick that ends the game) so that situations with a deterministic answer get a logical value rather than a smoothed one.</p>
<p>For each realized attempt from 2015-2025, we compare the head matching the actual outcome against nflfastR’s realized post-play win probability. Across 11,615 scored attempts the two agree closely (RMSE 0.045, MAE 0.032, <span class="math inline">\(R^2 = 0.975\)</span>), and the endgame overrides sharpen this agreement most where they are meant to with a 21.2% RMSE reduction in late-and-close situations versus 2.5% overall.</p>
<p>The full model formula is:</p>
<p><span class="math display">\[\log\frac{P(D_i = d)}{P(D_i = \text{Go})} = \alpha_d + \sum_{k=1}^{7} \beta_{d,k}\, b_k(\text{dist}_i) + \sum_{j=1}^{4} \gamma_{d,j}\, \text{ns}_j(t_i) + \delta_{d}\, \text{ydstogo}_i + \boldsymbol{\theta}_d^\top \mathbf{S}_i + \boldsymbol{\phi}_d^\top \mathbf{V}_i + \psi_d\, L_i + \text{time interactions}\]</span></p>
<p>where <span class="math inline">\(b_k\)</span> are B-spline basis functions evaluated at kick distance, <span class="math inline">\(\text{ns}_j\)</span> are natural spline basis functions evaluated at game seconds remaining <span class="math inline">\(t_i\)</span>, <span class="math inline">\(\mathbf{S}_i\)</span> is the vector of score-state indicators, <span class="math inline">\(\mathbf{V}_i\)</span> contains venue/weather indicators, and <span class="math inline">\(L_i\)</span> is game leverage. Each non-reference category <span class="math inline">\(d \in \{\text{FG}, \text{Punt}\}\)</span> has its own set of coefficients.</p>
</section>
<section id="training-protocol" class="level2">
<h2 class="anchored" data-anchor-id="training-protocol">3.3 Training Protocol</h2>
<p>A rolling-origin training protocol with a three-season window produced out-of-fold (OOF) predictions for each held-out season. For each target season <span class="math inline">\(s\)</span> (from 2015 onward), the model was trained on all fourth-down plays from seasons <span class="math inline">\(\{s-3, s-2, s-1\}\)</span> and predicted on season <span class="math inline">\(s\)</span>. This protocol prevents propensity score leakage into the outcome models and allows the propensity model to adapt to era-level shifts in coaching behavior over the 11-season sample.</p>
<p>The rolling window adapts to era drift only between folds, and within a fold it treats all three training seasons as exchangeable. Because fourth-down decision-making has moved steadily over the study period, the model additionally carries an explicit linear season trend. The trend is centered on each fold’s training-window mean and applied to the held-out season with that same centering constant, so the test season sits one step beyond the training center rather than being re-centered on itself.</p>
</section>
<section id="propensity-model-results" class="level2">
<h2 class="anchored" data-anchor-id="propensity-model-results">3.4 Propensity Model Results</h2>
<p>The propensity model consistently and accurately predicted coaching FG decisions across all 11 seasons (<a href="#tbl-propensity-auc" class="quarto-xref">Table&nbsp;2</a>). AUC ranged from 0.938 in 2022 to 0.961 in 2015, with a slight downward trend in the post-2020 period, possibly reflecting increased fourth-down conversion attempts as coaches absorbed analytics-driven guidance. The stability of propensity AUC across seasons validates the core assumption of the IPW framework, namely that attempt selection is a structured, predictable process rather than idiosyncratic noise.</p>
<div id="tbl-propensity-auc" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-propensity-auc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Propensity model (multinomial, rolling-origin OOF) AUC and Brier score by season.
</figcaption>
<div aria-describedby="tbl-propensity-auc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;">Season</th>
<th style="text-align: right;">AUC</th>
<th style="text-align: right;">Brier</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2015</td>
<td style="text-align: right;">0.961</td>
<td style="text-align: right;">0.075</td>
</tr>
<tr class="even">
<td style="text-align: right;">2016</td>
<td style="text-align: right;">0.958</td>
<td style="text-align: right;">0.078</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2017</td>
<td style="text-align: right;">0.957</td>
<td style="text-align: right;">0.079</td>
</tr>
<tr class="even">
<td style="text-align: right;">2018</td>
<td style="text-align: right;">0.959</td>
<td style="text-align: right;">0.080</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2019</td>
<td style="text-align: right;">0.950</td>
<td style="text-align: right;">0.089</td>
</tr>
<tr class="even">
<td style="text-align: right;">2020</td>
<td style="text-align: right;">0.944</td>
<td style="text-align: right;">0.095</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2021</td>
<td style="text-align: right;">0.940</td>
<td style="text-align: right;">0.098</td>
</tr>
<tr class="even">
<td style="text-align: right;">2022</td>
<td style="text-align: right;">0.938</td>
<td style="text-align: right;">0.100</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2023</td>
<td style="text-align: right;">0.944</td>
<td style="text-align: right;">0.095</td>
</tr>
<tr class="even">
<td style="text-align: right;">2024</td>
<td style="text-align: right;">0.940</td>
<td style="text-align: right;">0.098</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2025</td>
<td style="text-align: right;">0.943</td>
<td style="text-align: right;">0.098</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The rationality of coaching decisions is further illustrated by <a href="#fig-propensity-density" class="quarto-xref">Figure&nbsp;4</a>, which shows the distribution of propensity scores across decision types and demonstrates a clear separation in utility-driven coaching behavior. Both high-propensity and low-propensity field goal situations conform neatly to expectation and are clearly distinguishable.</p>
<div id="fig-propensity-density" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-propensity-density-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../../reports/figures/propensity_density_by_decision.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Figure&nbsp;4: Distribution of estimated field goal attempt propensity, by realized coaching decision."><img src="../../reports/figures/propensity_density_by_decision.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-propensity-density-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Distribution of estimated field goal attempt propensity, by realized coaching decision.
</figcaption>
</figure>
</div>
</section>
</section>
<section id="models-and-methods" class="level1">
<h1>4. Models and Methods</h1>
<section id="success-models" class="level2">
<h2 class="anchored" data-anchor-id="success-models">4.1 Success Models</h2>
<p>All outcome models were fitted using the glmmTMB R package with a logit link. Kick distance was encoded with the B-spline basis <span class="math inline">\(\mathbf{b}(d_i) = (b_1(d_i), \ldots, b_7(d_i))^\top\)</span> described in Section 2.2.</p>
<p><strong>M0 (distance baseline):</strong> A fixed-effects-only logistic regression on the B-spline distance basis, with no random effects and no environmental covariates. Serves as the distance-only predictive ceiling.</p>
<p><span class="math display">\[\text{logit}\bigl(P(Y_i = 1 \mid d_i)\bigr) = \sum_{k=1}^{7} \alpha_k b_k(d_i)\]</span></p>
<p><strong>M1 (full GLMM):</strong> The primary predictive model. Extends M0 with splined environmental covariates, contextual covariates, and two nested random effects:</p>
<p><span class="math display">\[\begin{aligned}
\text{logit}\bigl(P(Y_i=1 \mid X_i)\bigr) &amp;= \sum_{k=1}^{7}\alpha_k b_k(d_i)
  + \sum_{j=1}^{3}\beta^{w}_j\, n_j(w_i)
  + \sum_{j=1}^{3}\beta^{T}_j\, n_j(T_i)
  + \sum_{j=1}^{3}\beta^{H}_j\, n_j(H_i) \\
&amp;\quad + \gamma_1\,\text{turf}_i + \gamma_2\,\text{snow\_sleet}_i + \gamma_3\,\text{rain\_showers}_i + \gamma_4\,\text{clock\_running}_i \\
&amp;\quad + \gamma_5\,\text{iced}_i + \gamma_6\,\text{l2m}_i + \gamma_7(\text{clock\_running}_i \cdot \text{l2m}_i) + \gamma_8\,\text{playoffs}_i \\
&amp;\quad + u_{s(i)} + v_{g(i)}
\end{aligned}\]</span></p>
<p>where <span class="math inline">\(b_k(d_i)\)</span> is the <span class="math inline">\(k\)</span>-th B-spline basis function at distance <span class="math inline">\(d_i\)</span> (interior knots 28/38/48/58 yds, boundary knots 18/70 yds); <span class="math inline">\(n_j(\cdot)\)</span> denotes the <span class="math inline">\(j\)</span>-th natural cubic spline basis function (3 df) applied to standardized wind speed <span class="math inline">\(w_i\)</span>, standardized temperature <span class="math inline">\(T_i\)</span>, and standardized relative humidity <span class="math inline">\(H_i\)</span> respectively; <span class="math inline">\(u_{s(i)} \sim N(0, \sigma_s^2)\)</span> is a kicker-season random intercept; <span class="math inline">\(v_{g(i)} \sim N(0, \sigma_g^2)\)</span> is a stadium random intercept.</p>
<p>The weather covariates enter as additive spline main effects. A previous specification carried a wind-by-temperature product and a full set of wind-by-distance-spline interactions, and both are removed here. The interaction terms let wind sensitivity grow with distance, which is physically plausible, but they are estimated almost entirely from the sparse long-distance tail where the sample is thinnest, and the resulting model was not better out of sample. The present specification therefore assumes weather acts additively on the logit rather than amplifying with distance. We regard this as the more defensible default given the available sample and flag it as a modeling assumption rather than a finding.</p>
<p><strong>M2 (augmented GLMM):</strong> Our first attempt at the selection problem. If the difficulty with training only on observed attempts is that the declined kicks are missing, the direct remedy is to put them back. M2 is therefore the M1 formula fitted on a training set augmented with two additional sources of kicks. First, PAT attempts enter with their real, observed make/miss outcomes, carrying a reduced case weight (<code>aug_weight</code> = 0.10) rather than a weight of 1. They are not relabeled, so a missed PAT enters as a miss. Second, non-attempt fourth-down situations enter as pseudo-misses (<span class="math inline">\(Y_i = 0\)</span>) at the same reduced case weight, restricted to plays with estimated attempt propensity <span class="math inline">\(\hat{\pi}(X_i) \geq 0.25\)</span> and kick distance strictly greater than 33 yards. The propensity and distance restrictions apply to the non-attempts only, and all PATs are included. Non-attempts are the observations that the selection process removes, and including them, even imperfectly labeled, pushes the fitted curve back toward the difficulty distribution the coach declined.</p>
<p>The propensity floor of <span class="math inline">\(\hat{\pi} \geq 0.25\)</span> restricts the non-attempt pool to situations a coach could plausibly have kicked from. Below that threshold we assume the decision not to kick was driven by sound game-context reasons such as field position far out of range, a large deficit, or a short yards-to-go situation where going-for-it is prevalent, and that the play carries little information about a coach’s confidence in a kicker’s ability. The distance floor of 33 yards is set just beyond PAT range, since the post-2015 extra point is a roughly 33-yard kick. Inside that distance makes are near-certain and already well predicted, and a fourth-down non-attempt there reflects an aggressive strategic choice to go for it rather than any judgment about the kick, so labeling those plays as misses would be expected to only inject noise.</p>
<p>The non-attempt labeling is an approximation rather than ground truth. Every qualifying non-attempt beyond 33 yards is entered as a miss even though some fraction of those kicks would have been made, so the M2 training set is deliberately pessimistic in exactly the distance range the model is meant to learn about. This is the principal reason M2 is reported as exploratory rather than as a candidate predictor. The direction of its bias is known, and its magnitude is not identified from the data.</p>
<p>A declined kick with a true success probability near 0.3 should arguably not be scored as a 0. The outcome model requires a binary Bernoulli response, so a label must be assigned, and we damp the resulting distortion through the case weight rather than through the label. This is why <code>aug_weight</code> is a tuned hyperparameter rather than a fixed constant. Section 5.2 reports the sensitivity of M2 to that weight across a grid, and no configuration achieved a lower out-of-sample Brier score than M1. Fractional or model-imputed soft labels are a reasonable alternative that we did not adopt here, since they would make the pseudo-label depend on the very outcome model being fitted, and we preferred an approximation whose bias is transparent.</p>
<p><strong>M3 (IPW-weighted GLMM):</strong> The revised attempt, designed to represent a fuller universe of kickable situations without fabricating an outcome. Rather than imputing labels for kicks that never happened, M3 reweights the kicks that did happen so that the observed sample stands in for that fuller universe. It is the M1 formula fitted with case weights <span class="math inline">\(w_i^H\)</span> (Hajek-normalized, <span class="math inline">\(3\sigma\)</span>-capped stabilized propensity weights, as defined in Section 2.3). By upweighting rare difficult attempts, M3 is designed to estimate probabilities closer to the population-average distribution rather than the coaching-selected attempt distribution. Every observation it uses carries an outcome that was actually observed, which is precisely the weakness of M2. The price is variance rather than bias, where a handful of long, low-propensity attempts carry weights several times those of a routine kick, so the tail of the distance curve is estimated from an effectively smaller sample than the raw counts suggest.</p>
<p><strong>M3-pop (population marginal, for FGOE):</strong> A kicker-neutral baseline that estimates the kick probability for a given context <span class="math inline">\(X_i\)</span> independent of individual kicker ability, used to compute FGOE. This is discussed further in Section 6.</p>
</section>
<section id="evaluation-metrics" class="level2">
<h2 class="anchored" data-anchor-id="evaluation-metrics">4.2 Evaluation Metrics</h2>
<p>Primary predictive metrics are Brier score (lower is better), log-loss (lower is better), and AUC (higher is better), computed separately on the in-sample (IS) training set and the held-out test set (OOS). Log-loss is reported alongside Brier because it penalizes confident errors more sharply and is the more sensitive of the two to miscalibration in the probability tails, which is precisely where the IPW correction is expected to act. A secondary metric is calibration error by distance band, defined as the mean absolute difference between the observed make rate and the mean predicted probability within five distance bands (&lt;30, 30-39, 40-49, 50-59, 60+ yards).</p>
<p><strong>IS vs.&nbsp;OOS claim policy:</strong> A model is claimed to improve on M1 only if it achieves a strictly lower Brier score on the held-out test set. In-sample Brier improvements alone are treated as descriptive evidence of bias correction, not predictive improvement.</p>
</section>
<section id="inference-and-robustness-policy" class="level2">
<h2 class="anchored" data-anchor-id="inference-and-robustness-policy">4.3 Inference and Robustness Policy</h2>
<p>M2 is classified as exploratory for two reasons. It does not achieve a lower OOS Brier score than M1 under any tested weighting configuration (Section 5.2), and its non-attempt pseudo-labels are a known-biased approximation rather than observed outcomes (Section 4.1). Distance-band calibration diagnostics (Section 5.3) are interpreted as directional evidence only, not as formal inference. The 60+ yard band contains <span class="math inline">\(n = 77\)</span> in-sample observations, so point estimates in this cell carry high uncertainty. All evaluation is restricted to non-blocked FG attempts.</p>
</section>
</section>
<section id="modeling-results" class="level1">
<h1>5. Modeling Results</h1>
<section id="predictive-benchmark-across-models" class="level2">
<h2 class="anchored" data-anchor-id="predictive-benchmark-across-models">5.1 Predictive Benchmark Across Models</h2>
<p>The in-sample (IS) metrics reported throughout this section are calculated over the full dataset (<span class="math inline">\(n = 11{,}548\)</span>) using predictions from the models fitted on the full dataset (Option B). For the augmented model (M2), these metrics are evaluated exclusively on actual field goal attempts, omitting the PAT and non-attempt rows used during training. All reported Brier scores are standard, unweighted metrics to maintain direct comparability.</p>
<p><a href="#tbl-model-metrics" class="quarto-xref">Table&nbsp;3</a> presents global predictive metrics on the IS and OOS splits for all four models. M3 achieves the best IS fit on every metric (Brier 0.0982, log-loss 0.3216, AUC 0.806). On the OOS test set the ordering reverses and M1 outperforms all models on every metric (Brier 0.1004, log-loss 0.3295, AUC 0.769). M3 OOS Brier (0.1026) exceeds even M0 (0.1012), evidence that IPW variance inflation from extreme long-range weights degrades prediction in the 2,251-observation test set. M2 sits between the two, improving on neither M1 split. Log-loss and Brier agree on the ranking in both splits, so the reversal is not an artifact of the choice of proper scoring rule.</p>
<div id="tbl-model-metrics" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-model-metrics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Model performance on in-sample (IS, <span class="math inline">\(n = 11{,}548\)</span>) and held-out test set (OOS, <span class="math inline">\(n = 2{,}251\)</span>). Brier and log-loss: lower is better. AUC: higher is better. Blocked kicks excluded. Bold indicates best value in column.
</figcaption>
<div aria-describedby="tbl-model-metrics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th style="text-align: right;">IS Brier</th>
<th style="text-align: right;">IS Log-Loss</th>
<th style="text-align: right;">IS AUC</th>
<th style="text-align: right;">OOS Brier</th>
<th style="text-align: right;">OOS Log-Loss</th>
<th style="text-align: right;">OOS AUC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>M0 (distance only)</td>
<td style="text-align: right;">0.1045</td>
<td style="text-align: right;">0.3387</td>
<td style="text-align: right;">0.774</td>
<td style="text-align: right;">0.1012</td>
<td style="text-align: right;">0.3323</td>
<td style="text-align: right;">0.762</td>
</tr>
<tr class="even">
<td>M1 (full GLMM)</td>
<td style="text-align: right;">0.1004</td>
<td style="text-align: right;">0.3259</td>
<td style="text-align: right;">0.804</td>
<td style="text-align: right;"><strong>0.1004</strong></td>
<td style="text-align: right;"><strong>0.3295</strong></td>
<td style="text-align: right;"><strong>0.769</strong></td>
</tr>
<tr class="odd">
<td>M2 (augmented)</td>
<td style="text-align: right;">0.1009</td>
<td style="text-align: right;">0.3281</td>
<td style="text-align: right;">0.800</td>
<td style="text-align: right;">0.1015</td>
<td style="text-align: right;">0.3325</td>
<td style="text-align: right;">0.766</td>
</tr>
<tr class="even">
<td>M3 (IPW)</td>
<td style="text-align: right;"><strong>0.0982</strong></td>
<td style="text-align: right;"><strong>0.3216</strong></td>
<td style="text-align: right;"><strong>0.806</strong></td>
<td style="text-align: right;">0.1026</td>
<td style="text-align: right;">0.3367</td>
<td style="text-align: right;">0.761</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The calibration of each model is shown directly in <a href="#fig-calibration" class="quarto-xref">Figure&nbsp;5</a>. Predicted probabilities are binned into deciles of predicted value and plotted against the observed make rate within each bin, with 95% Wilson intervals so that departures from the diagonal can be read against their own sampling error, and with the distribution of predicted probabilities shown beneath each panel. Two features are worth noting. First, all four models are well calibrated in the high-probability bins, which is where the great majority of kicks sit. Second, all four sit above the diagonal through the middle of the range, roughly 0.70 to 0.90 predicted, meaning they modestly under-predict success on kicks of intermediate difficulty. Individual bin deviations are mostly within their Wilson intervals, but the sign is consistent across bins and across models, so the pattern is systematic rather than noise. It is also common to all four specifications, including the distance-only M0, which indicates it reflects something about the outcome model family rather than anything introduced by the IPW correction. M3 shows the largest deviation in its lowest bin (observed 0.668 against 0.563 predicted), consistent with the upweighting of difficult attempts pulling its predictions downward in the tail.</p>
<div id="fig-calibration" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-calibration-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../../reports/figures/calibration_test.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5" title="Figure&nbsp;5: Calibration by decile of predicted probability, held-out test set."><img src="../../reports/figures/calibration_test.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-calibration-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Calibration by decile of predicted probability, held-out test set.
</figcaption>
</figure>
</div>
<p><a href="#fig-separation" class="quarto-xref">Figure&nbsp;6</a> illustrates the in-sample distribution of predicted probabilities for made versus missed kicks across models, indicating how well M1 and M3 distinguish outcomes. M3 pushes low-probability kicks leftward, clarifying the distinct separation profile for missed kicks.</p>
<div id="fig-separation" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-separation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../../reports/figures/separation_density.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6" title="Figure&nbsp;6: In-sample distribution of predicted make probability, separated by realized outcome."><img src="../../reports/figures/separation_density.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-separation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: In-sample distribution of predicted make probability, separated by realized outcome.
</figcaption>
</figure>
</div>
</section>
<section id="m2-augmentation-with-pseudo-labels" class="level2">
<h2 class="anchored" data-anchor-id="m2-augmentation-with-pseudo-labels">5.2 M2: Augmentation with Pseudo-Labels</h2>
<p>M2 was the first correction we built, and the four-model table above demonstrates the limitations in its design. Adding the declined kicks back into the training universe did not recover the difficulty distribution coaches selectively removed.</p>
<p>More augmentation makes prediction worse, not better. M2 was evaluated across a grid of augmentation case weights, applied symmetrically to the PAT rows (which carry observed outcomes) and the non-attempt rows (which carry pseudo-miss labels). Across all configurations, M2 did not achieve a lower OOS Brier score than M1. Within the grid the degradation is monotone in the weight (<a href="#tbl-m2-grid" class="quarto-xref">Table&nbsp;4</a>). In-sample Brier rises from 0.1007 at weight 0.05 to 0.1009 at 0.10 and 0.1016 at 0.25, log-loss rises in step from 0.3272 to 0.3304, and in-sample calibration error nearly doubles from 0.0145 to 0.0285. If the pseudo-misses carried real information about the declined kicks, leaning on them harder should help. It does the opposite, which is the signature of a label that is systematically wrong rather than merely noisy. The primary configuration (weight = 0.10) produced OOS Brier 0.1015, which underperforms M1. M2 is retained as an exploratory lens for long-distance tail behavior but should not be used as a production predictor.</p>
<div id="tbl-m2-grid" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-m2-grid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: M2 weight sensitivity grid (PAT weight = Non-attempt weight). IS metrics only. OOS Brier for the primary 0.10 configuration is 0.1015.
</figcaption>
<div aria-describedby="tbl-m2-grid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;">PAT/Non Weight</th>
<th style="text-align: right;">IS Brier</th>
<th style="text-align: right;">IS Log-Loss</th>
<th style="text-align: right;">IS AUC</th>
<th style="text-align: right;">IS Calib. Error</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">0.1007</td>
<td style="text-align: right;">0.3272</td>
<td style="text-align: right;">0.801</td>
<td style="text-align: right;">0.0145</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">0.1009</td>
<td style="text-align: right;">0.3281</td>
<td style="text-align: right;">0.800</td>
<td style="text-align: right;">0.0166</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">0.1016</td>
<td style="text-align: right;">0.3304</td>
<td style="text-align: right;">0.801</td>
<td style="text-align: right;">0.0285</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Another finding is that the PAT block turns out to contribute essentially nothing. The augmentation combines two very different sources, namely PATs with observed outcomes and non-attempts with imputed pseudo-miss labels, so we refit M2 with the PAT block removed to isolate what each contributes. The two variants are near-indistinguishable, and if anything the PAT-free version is marginally the better of the two. In sample its Brier is 0.1005 versus 0.1009 and its log-loss 0.3270 versus 0.3281. Out of sample its Brier is 0.1013 versus 0.1015 and its log-loss 0.3321 versus 0.3325. Neither approaches M1 out of sample. The motivating intuition for including PATs, that a dense block of short and essentially unselected kicks would sharpen the model, is therefore not borne out. The plausible reason is that the region PATs inform (roughly 33 yards, where make probability is near 0.95) is already the best-determined part of the distance curve, so the additional rows contribute little beyond what the 3,017 sub-30-yard field goals already supply.</p>
<p>Taken together, these two results are what moved us off the direct augmentation approach. The problem is not the size of the augmented sample or the tuning of its weight but the labels themselves, since every declined kick beyond 33 yards is entered as a miss when some fraction of them would have been made. No choice of weight fixes a label that is wrong in a known direction. That is what M3 is designed to avoid.</p>
</section>
<section id="m3-inverse-probability-weighting-and-the-distance-tail" class="level2">
<h2 class="anchored" data-anchor-id="m3-inverse-probability-weighting-and-the-distance-tail">5.3 M3: Inverse Probability Weighting and the Distance Tail</h2>
<p>M3 reaches the same target without inventing any outcome, and in-sample it does what the augmentation could not. <a href="#tbl-dist-brier" class="quarto-xref">Table&nbsp;5</a> reports in-sample Brier score within each distance band.</p>
<div id="tbl-dist-brier" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-dist-brier-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: In-sample Brier score by distance band. Lower is better. Bold: best value in row.
</figcaption>
<div aria-describedby="tbl-dist-brier-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Distance Band</th>
<th>Sample Count (N)</th>
<th style="text-align: right;">M0</th>
<th style="text-align: right;">M1</th>
<th style="text-align: right;">M2</th>
<th style="text-align: right;">M3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>&lt; 30 yds</td>
<td>3,017</td>
<td style="text-align: right;">0.0171</td>
<td style="text-align: right;">0.0171</td>
<td style="text-align: right;">0.0171</td>
<td style="text-align: right;">0.0171</td>
</tr>
<tr class="even">
<td>30-39 yds</td>
<td>3,314</td>
<td style="text-align: right;">0.0624</td>
<td style="text-align: right;"><strong>0.0611</strong></td>
<td style="text-align: right;">0.0614</td>
<td style="text-align: right;">0.0614</td>
</tr>
<tr class="odd">
<td>40-49 yds</td>
<td>3,407</td>
<td style="text-align: right;">0.1643</td>
<td style="text-align: right;">0.1575</td>
<td style="text-align: right;">0.1582</td>
<td style="text-align: right;"><strong>0.1568</strong></td>
</tr>
<tr class="even">
<td>50-59 yds</td>
<td>1,733</td>
<td style="text-align: right;">0.2141</td>
<td style="text-align: right;">0.2030</td>
<td style="text-align: right;">0.2044</td>
<td style="text-align: right;"><strong>0.1917</strong></td>
</tr>
<tr class="odd">
<td>60+ yds</td>
<td>77</td>
<td style="text-align: right;">0.2249</td>
<td style="text-align: right;">0.2172</td>
<td style="text-align: right;">0.2208</td>
<td style="text-align: right;"><strong>0.1692</strong></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>M3 achieves a 5.6% Brier reduction versus M1 at 50-59 yards and a 22.1% reduction at 60+ yards in-sample.</p>
<p>The models diverge at 50+ yards, where the IPW correction in M3 has the most leverage. M2 is flat to slightly worse than M1 across the same bands, so the tail gain belongs to the reweighting rather than to bias correction in general. However, the 60+ yard distance band contains only <span class="math inline">\(n = 77\)</span> in-sample observations, meaning point estimates in this range carry high uncertainty.</p>
<p>To evaluate model performance across the distance spectrum, <a href="#fig-brier-curve" class="quarto-xref">Figure&nbsp;7</a> plots continuous squared residuals (Brier error) smoothed using a LOESS fit, side by side for in-sample training and out-of-sample test data.</p>
<div id="fig-brier-curve" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-brier-curve-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../../reports/figures/brier_comparison_is_oos.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7" title="Figure&nbsp;7: LOESS-smoothed squared error by kick distance, in-sample and out-of-sample."><img src="../../reports/figures/brier_comparison_is_oos.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-brier-curve-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: LOESS-smoothed squared error by kick distance, in-sample and out-of-sample.
</figcaption>
</figure>
</div>
<p>In-sample, M3 achieves lower squared error than M1 at long distances, demonstrating the effect of the IPW correction. However, out-of-sample, the error curves cross, and M1 outperforms M3, confirming that M3’s fit to tail noise in the training set does not generalize. The correction is therefore real and visible where it was designed to act, and it still does not buy held-out accuracy.</p>
</section>
<section id="era-stability-of-the-selection-bias-result" class="level2">
<h2 class="anchored" data-anchor-id="era-stability-of-the-selection-bias-result">5.4 Era Stability of the Selection-Bias Result</h2>
<p>Coaching fourth-down behavior changed materially over the study window, which raises the possibility that the selection-bias question has different answers in different eras. If coaches selected attempts more idiosyncratically early in the sample and more systematically later, the value of a propensity correction could differ between the two. We therefore re-ran the M1-versus-M3 comparison separately on pre-2020 (2015-2019) and post-2020 (2020-2025) held-out kicks, reported in <a href="#tbl-era-oos" class="quarto-xref">Table&nbsp;6</a>.</p>
<div id="tbl-era-oos" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-era-oos-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Out-of-sample M1 vs.&nbsp;M3 by era. Lower is better; bold indicates the better value.
</figcaption>
<div aria-describedby="tbl-era-oos-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th>Era</th>
<th style="text-align: right;">Test kicks</th>
<th style="text-align: right;">M1 Brier</th>
<th style="text-align: right;">M3 Brier</th>
<th style="text-align: right;">M1 Log-Loss</th>
<th style="text-align: right;">M3 Log-Loss</th>
<th>Better model</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Pre-2020 (2015-2019)</td>
<td style="text-align: right;">976</td>
<td style="text-align: right;"><strong>0.1105</strong></td>
<td style="text-align: right;">0.1132</td>
<td style="text-align: right;"><strong>0.3583</strong></td>
<td style="text-align: right;">0.3676</td>
<td>M1</td>
</tr>
<tr class="even">
<td>Post-2020 (2020-2025)</td>
<td style="text-align: right;">1,275</td>
<td style="text-align: right;"><strong>0.0928</strong></td>
<td style="text-align: right;">0.0945</td>
<td style="text-align: right;"><strong>0.3074</strong></td>
<td style="text-align: right;">0.3131</td>
<td>M1</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The answer does not change. M1 is the better out-of-sample model in both eras, on both scoring rules, and the margin is of similar size in each (Brier gap 0.0027 pre-2020, 0.0018 post-2020). The absolute error level differs substantially between eras, since every model predicts post-2020 kicks better than pre-2020 kicks, which is consistent with the increased consistency of modern kicking documented in Section 7. That is a change in the difficulty of the prediction problem rather than in the usefulness of the selection correction. We therefore report the selection-bias finding as stable across the sample rather than era-dependent.</p>
</section>
</section>
<section id="fgoe-and-player-evaluations" class="level1">
<h1>6. FGOE and Player Evaluations</h1>
<p>FGOE is a per-kick residual metric that quantifies how much a kicker outperformed (or underperformed) the context-neutral expected make probability. Over the 11-season period analyzed (2015-2025), FGOE is defined as:</p>
<p><span class="math display">\[\text{FGOE}_i = Y_i - \hat{p}_{\text{M3-pop}}(X_i)\]</span></p>
<p>where <span class="math inline">\(\hat{p}_{\text{M3-pop}}(X_i)\)</span> is the M3-pop predicted probability for kick <span class="math inline">\(i\)</span>, computed from the fitted M3 with the kicker-season random intercept set to zero and the stadium effect retained (Section 4.1). Because the kicker term is removed, <span class="math inline">\(\hat{p}_{\text{M3-pop}}\)</span> reflects the probability a typical kicker would achieve for a kick of context <span class="math inline">\(X_i\)</span> at that venue, independent of the individual kicker’s ability. This design ensures that FGOE is attributable to the kicker rather than confounded by stadium effects.</p>
<p>We determined that zeroing the kicker term is preferable to refitting the model without it. On held-out kicks the refit variant is more biased than the zeroed variant in the 60+ yard band (mean predicted minus observed +0.332 versus +0.277, Brier 0.267 versus 0.242), because a refit must re-absorb the systematic component of kicker ability into the distance basis, which is the only place in the model with the flexibility to hold it.</p>
<p>Cumulative FGOE over a kicker-season <span class="math inline">\((k, s)\)</span> is:</p>
<p><span class="math display">\[\text{FGOE}_{k,s} = \sum_{i:\,\text{kicker}=k,\,\text{season}=s} \text{FGOE}_i\]</span></p>
<p>A kicker with <span class="math inline">\(\text{FGOE}_{k,s} &gt; 0\)</span> made more kicks than the context-adjusted baseline predicted; <span class="math inline">\(\text{FGOE}_{k,s} &lt; 0\)</span> indicates underperformance. Unlike raw make rate, FGOE is adjusted for distance distribution, weather, and surface, making it a fairer basis for cross-kicker comparison.</p>
<p>The FGOE leaderboard ranks kicker-seasons by cumulative FGOE. Top-ranked kicker-seasons are concentrated among kickers with consistently high make rates across a variety of distance and weather profiles, not simply those who attempted the most kicks. <a href="#fig-fgoe-total" class="quarto-xref">Figure&nbsp;8</a> and <a href="#fig-fgoe-rate" class="quarto-xref">Figure&nbsp;9</a> present the career-level rankings on a total and a per-kick basis respectively.</p>
<div id="fig-fgoe-total" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fgoe-total-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../../reports/figures/fgoe_leaderboard.png" class="lightbox" data-gallery="quarto-lightbox-gallery-8" title="Figure&nbsp;8: Career FGOE leaderboard, ranked by cumulative FGOE."><img src="../../reports/figures/fgoe_leaderboard.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fgoe-total-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: Career FGOE leaderboard, ranked by cumulative FGOE.
</figcaption>
</figure>
</div>
<div id="fig-fgoe-rate" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fgoe-rate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../../reports/figures/fgoe_rate_leaderboard.png" class="lightbox" data-gallery="quarto-lightbox-gallery-9" title="Figure&nbsp;9: Career FGOE leaderboard, ranked by FGOE per attempt."><img src="../../reports/figures/fgoe_rate_leaderboard.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fgoe-rate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: Career FGOE leaderboard, ranked by FGOE per attempt.
</figcaption>
</figure>
</div>
<p><a href="#fig-skill-workload" class="quarto-xref">Figure&nbsp;10</a> confirms that high-FGOE kickers appear across workload levels, suggesting FGOE captures ability independently of attempt volume. However, there is clearly survivorship bias as kickers who remianed in the league long enough to attempt 200+ kicks are at least close to break-even with expection, with the majority above average.</p>
<div id="fig-skill-workload" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-skill-workload-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../../reports/figures/skill_vs_workload_scatter.png" class="lightbox" data-gallery="quarto-lightbox-gallery-10" title="Figure&nbsp;10: Career FGOE against attempt volume."><img src="../../reports/figures/skill_vs_workload_scatter.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-skill-workload-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10: Career FGOE against attempt volume.
</figcaption>
</figure>
</div>
<p>To examine this workload distribution itself, <a href="#fig-workload-propensity" class="quarto-xref">Figure&nbsp;11</a> plots average attempt distance against the mean propensity to attempt kicks.</p>
<div id="fig-workload-propensity" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-workload-propensity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../../reports/figures/kicker_workload_propensity.png" class="lightbox" data-gallery="quarto-lightbox-gallery-11" title="Figure&nbsp;11: Mean attempt distance against mean attempt propensity, by kicker."><img src="../../reports/figures/kicker_workload_propensity.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-workload-propensity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11: Mean attempt distance against mean attempt propensity, by kicker.
</figcaption>
</figure>
</div>
<p>The relationship is clearly negative. Kickers who average longer-range attempts also face a lower mean attempt propensity, and consequently higher average IPW weights. This highlights how FGOE controls for the selective difficulty distribution faced by trusted kickers. Brandon Aubrey’s attempts were the furthest on average and least likely to have been attempted.</p>
</section>
<section id="field-goal-kicking-trends" class="level1">
<h1>7. Field Goal Kicking Trends</h1>
<p>Two conventions apply throughout this section. First, “short-yardage” and “long-yardage” refer only to how far a team is from the end zone, while the yards needed for a first down are described as <strong>short yards-to-go</strong> (4 or fewer) and <strong>long yards-to-go</strong> (5 or more). Second, the coaching-decision figures in Sections 7.1 and 7.2 (<a href="#fig-decision-fieldpos" class="quarto-xref">Figure&nbsp;16</a>, <a href="#fig-short-ytg-era" class="quarto-xref">Figure&nbsp;17</a>, <a href="#fig-wpa-era" class="quarto-xref">Figure&nbsp;18</a>, and <a href="#fig-wpa-ytg" class="quarto-xref">Figure&nbsp;19</a>) plot <strong>yards from the end zone</strong> on the horizontal axis, not kick distance. Most other figures in the paper use kick distance, which is roughly 17 yards greater.</p>
<p>A major influence on the coaching decision framework has been the steady improvement in kicker accuracy and range over the past decade. Average field goal attempt distances have risen, and the share of attempts from beyond 50 yards has grown substantially. This shift is visible in the season-level kicking trends in <a href="#fig-season-trends" class="quarto-xref">Figure&nbsp;12</a>, with the 2015-2025 modeling period shaded.</p>
<div id="fig-season-trends" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-season-trends-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../../reports/figures/season_kicking_trends_detailed.png" class="lightbox" data-gallery="quarto-lightbox-gallery-12" title="Figure&nbsp;12: Season-level field goal attempt distance, make rate, and long-range attempt share, 2000-2025."><img src="../../reports/figures/season_kicking_trends_detailed.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-season-trends-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12: Season-level field goal attempt distance, make rate, and long-range attempt share, 2000-2025.
</figcaption>
</figure>
</div>
<p>The average field goal attempt distance has steadily increased over time, climbing by nearly 5 yards since 2000. While overall make rates improved consistently up to 2015 (the beginning of the modeling period), they have largely stabilized since. This stabilization has occurred despite the ongoing rise in average kick distance, particularly for attempts from 50 yards or more, which have increased substantially since the 2020 season. Kickers have maintained their overall accuracy and even demonstrated continued improvement on 50-plus yard kicks, converting longer and more difficult attempts on average. Given the distinct shift in attempt frequency and accuracy for deep kicks starting around 2020, some subsequent visual analyses are partitioned into pre-2020 and post-2020 eras.</p>
<p>As kickers have improved, the distribution of field goal attempt distances has shifted rightward (longer) over the study period, as <a href="#fig-dist-shift" class="quarto-xref">Figure&nbsp;13</a> shows.</p>
<div id="fig-dist-shift" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dist-shift-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../../reports/figures/kick_distance_distribution_15vs25.png" class="lightbox" data-gallery="quarto-lightbox-gallery-13" title="Figure&nbsp;13: Distribution of field goal attempt distance, 2015 versus 2025."><img src="../../reports/figures/kick_distance_distribution_15vs25.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dist-shift-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13: Distribution of field goal attempt distance, 2015 versus 2025.
</figcaption>
</figure>
</div>
<p>To further illustrate how the kicking environment has changed, <a href="#fig-make-rate-era" class="quarto-xref">Figure&nbsp;14</a> shows that post-2020 kickers convert at higher rates from long range relative to the pre-2020 period.</p>
<div id="fig-make-rate-era" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-make-rate-era-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../../reports/figures/make_rate_by_distance_era.png" class="lightbox" data-gallery="quarto-lightbox-gallery-14" title="Figure&nbsp;14: Make rate by kick distance, pre-2020 versus post-2020."><img src="../../reports/figures/make_rate_by_distance_era.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-make-rate-era-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14: Make rate by kick distance, pre-2020 versus post-2020.
</figcaption>
</figure>
</div>
<p>These improvements in kicker capability have shifted the boundaries of what coaches consider a viable attempt, changing the composition of the observed kick sample over time.</p>
<section id="decision-evolution-by-yardage-context" class="level2">
<h2 class="anchored" data-anchor-id="decision-evolution-by-yardage-context">7.1 Decision Evolution by Yardage Context</h2>
<p>Coaching fourth-down decisions are not driven by a single universal calculus. The strategic trade-offs differ substantially depending on how many yards remain to gain a first down, which is entirely distinct from kick distance or field position. To capture this, we split fourth-down situations in <a href="#fig-decision-evolution" class="quarto-xref">Figure&nbsp;15</a> by whether the team faces long yards-to-go (5 or more) or short yards-to-go (4 or fewer).</p>
<div id="fig-decision-evolution" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-decision-evolution-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../../reports/figures/kicking_decision_evolution.png" class="lightbox" data-gallery="quarto-lightbox-gallery-15" title="Figure&nbsp;15: Evolution of fourth-down decision shares by season, split by yards-to-go regime."><img src="../../reports/figures/kicking_decision_evolution.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-decision-evolution-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;15: Evolution of fourth-down decision shares by season, split by yards-to-go regime.
</figcaption>
</figure>
</div>
<p>On fourth downs with long yards-to-go (5 or more for a first down), punting has historically been and remains the dominant choice. Field goals have gained share from punts over the observed period as kicker range and accuracy improved. Go-for-it rates in this regime have not increased dramatically, which is expected. Converting 5 or more yards on a single play is a difficult proposition, and the expected value of going for it does not typically exceed the value of a makeable field goal attempt.</p>
<p>On fourth downs with short yards-to-go (4 or fewer), the story is markedly different. Coaches have dramatically shifted away from both punts and field goals in favor of go-for-it conversion attempts. This shift reflects the analytics-driven recognition that when a conversion is likely, the expected value of gaining a first down or touchdown (if in a goal-to-go scenario) often exceeds the value of a field goal, even as kickers have improved. The field position decision profiles in <a href="#fig-decision-fieldpos" class="quarto-xref">Figure&nbsp;16</a> confirm how these patterns play out across the field.</p>
<div id="fig-decision-fieldpos" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-decision-fieldpos-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../../reports/figures/decision_by_field_position.png" class="lightbox" data-gallery="quarto-lightbox-gallery-16" title="Figure&nbsp;16: Fourth-down decision shares by field position, split by yards-to-go regime."><img src="../../reports/figures/decision_by_field_position.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-decision-fieldpos-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;16: Fourth-down decision shares by field position, split by yards-to-go regime.
</figcaption>
</figure>
</div>
<p>With long yards-to-go, field goals are the preferred choice inside approximately 35 yards from the end zone, whereas punting dominates from further out. With short yards-to-go, kicking remains the primary option until about 30 yards from the end zone, with the notable exception of the 1-yard line, where going for it dominates. Go-for-it rates peak around 40 yards from the end zone, where a field goal attempt would require a difficult 55-plus yard kick with a lower conversion probability.</p>
<p>The era comparison for short yards-to-go situations in <a href="#fig-short-ytg-era" class="quarto-xref">Figure&nbsp;17</a> illustrates how pronounced the post-2020 shift has been.</p>
<div id="fig-short-ytg-era" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-short-ytg-era-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../../reports/figures/short_yardage_decisions_era.png" class="lightbox" data-gallery="quarto-lightbox-gallery-17" title="Figure&nbsp;17: Fourth-down decision shares on short yards-to-go by field position, pre-2020 versus post-2020."><img src="../../reports/figures/short_yardage_decisions_era.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-short-ytg-era-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;17: Fourth-down decision shares on short yards-to-go by field position, pre-2020 versus post-2020.
</figcaption>
</figure>
</div>
<p>Post-2020 coaches are far more likely to go for it on fourth down with short yards-to-go at almost every field position relative to the pre-2020 era, with field goal and punt rates declining accordingly.</p>
</section>
<section id="win-probability-added-and-the-decision-framework" class="level2">
<h2 class="anchored" data-anchor-id="win-probability-added-and-the-decision-framework">7.2 Win Probability Added and the Decision Framework</h2>
<p>To analyze how coaching decisions on fourth down align with observed results, we use win probability added (WPA). The WPA curves in <a href="#fig-wpa-era" class="quarto-xref">Figure&nbsp;18</a> compare the average win probability gained from field goals, punts, and go-for-it plays across field positions, split by era.</p>
<div id="fig-wpa-era" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-wpa-era-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../../reports/figures/wpa_landscape_by_era.png" class="lightbox" data-gallery="quarto-lightbox-gallery-18" title="Figure&nbsp;18: Average win probability added by decision type and field position, pre-2020 versus post-2020."><img src="../../reports/figures/wpa_landscape_by_era.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-wpa-era-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;18: Average win probability added by decision type and field position, pre-2020 versus post-2020.
</figcaption>
</figure>
</div>
<p>WPA from long field goals has increased alongside kicker improvement, and the post-2020 era shows the highest expected WPA from go-for-it plays concentrated around midfield. The differences between eras in the WPA curves, while real, are modest in magnitude, which is consistent with the finding that kicker selection bias does not substantially distort model performance.</p>
<p>Stratifying WPA by yards-to-go regime in <a href="#fig-wpa-ytg" class="quarto-xref">Figure&nbsp;19</a> reveals the distinct decision logic more clearly.</p>
<div id="fig-wpa-ytg" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-wpa-ytg-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../../reports/figures/wpa_by_ytg_regime.png" class="lightbox" data-gallery="quarto-lightbox-gallery-19" title="Figure&nbsp;19: Average win probability added by decision type and field position, split by yards-to-go regime."><img src="../../reports/figures/wpa_by_ytg_regime.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-wpa-ytg-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;19: Average win probability added by decision type and field position, split by yards-to-go regime.
</figcaption>
</figure>
</div>
<p>When facing a fourth down with long yards-to-go, the field goal is the better-expected-value option until roughly 40 yards from the end zone, where the WPA curves begin to converge. With short yards-to-go, the go-for-it option carries positive WPA across the entire field within 70 yards, and field goal attempts are associated with negative WPA at virtually all distances. This would suggest that even more aggressive behavior in that regime could be justified by the data, and the post-2020 trend reflects coaches moving in that direction.</p>
<p><a href="#fig-density-wpa" class="quarto-xref">Figure&nbsp;20</a> maps the post-2020 kick attempt density onto the corresponding WPA curve for field goals, illustrating where in the distance distribution coaches are actually operating relative to where the WPA advantage lies.</p>
<div id="fig-density-wpa" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-density-wpa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../../reports/figures/kick_density_on_wpa.png" class="lightbox" data-gallery="quarto-lightbox-gallery-20" title="Figure&nbsp;20: Post-2020 field goal attempt density overlaid on the field goal WPA curve."><img src="../../reports/figures/kick_density_on_wpa.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-density-wpa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;20: Post-2020 field goal attempt density overlaid on the field goal WPA curve.
</figcaption>
</figure>
</div>
<p>Coaches’ decisions and the expected win probability added display highly consistent patterns across distances. This alignment suggests that coaches possess a structured understanding of the distance thresholds at which field goal attempts contribute positively to win probability, likely driven by a combination of historical intuition and modern analytics. However, the WPA curves also indicate room for greater aggressiveness beyond 45 yards, as the expected WPA for field goals peaks at approximately 55 yards. The rapid improvement in long-range kicking accuracy in recent years suggests that coaching behavior may still be adapting to this enhanced capability. Additionally, the relationship between decisions and expected value is complex. With short yards-to-go, for instance, conversion attempts are universally superior to field goals, indicating that simple distance-based guidelines are insufficient. Ultimately, this selective coaching process is the exact mechanism that generates the sample selection bias addressed by the inverse probability weighting framework.</p>
</section>
</section>
<section id="discussion" class="level1">
<h1>8. Discussion</h1>
<section id="why-corrective-models-do-not-win-out-of-sample-prediction" class="level2">
<h2 class="anchored" data-anchor-id="why-corrective-models-do-not-win-out-of-sample-prediction">8.1 Why Corrective Models Do Not Win Out-of-Sample Prediction</h2>
<p>The three models encode qualitatively different estimands. M1 estimates the conditional success probability for observed FG attempts, a quantity well-suited to in-game decision support but one that inherits the selection structure of coaching behavior. M2 approximates the population-average probability across all kickable situations by imputing pseudo-labels for non-attempts, but the pseudo-label mechanism introduces bias in a known direction that prevents any calibration gain from translating into predictive improvement. M3 targets that same population-average quantity by reweighting rather than imputing, which removes the label problem entirely, at the cost of higher variance in the long-distance tail.</p>
<p>We are not persuaded that with more data M3 would eventually outperform M1 out-of-sample. The pattern in our results is consistent with IPW shifting fitting effort toward the sparse, high-variance extreme tails. M3’s in-sample gains are concentrated in the 50+ yard bands where weights are largest and sample counts smallest, and its out-of-sample deficit relative to M1 appears at the medium distances that make up the bulk of the test set. We describe this as the pattern the evidence shows rather than as a demonstrated mechanism, since we did not isolate the variance contribution of the weights directly.</p>
<p>One competing explanation can be set aside. If the held-out games had happened to draw an unusual mix of kick distances, M3’s deficit could be an artifact of the split rather than a property of the correction. <a href="#tbl-split-balance" class="quarto-xref">Table&nbsp;1</a> shows this is not the case: the training and held-out attempt distributions are closely matched on distance, estimated propensity, and weight magnitude, and the residual imbalance is smaller than a typical redraw under the same design (<span class="math inline">\(p = 0.68\)</span>). What this does <em>not</em> rule out is the broader version of the same idea, that the reweighted target is itself a worse match to the attempt distribution any held-out sample of observed kicks will have. That mismatch is not a sampling accident but the design of IPW, which deliberately moves the estimation target away from the observed attempt mix; it remains consistent with our results and is not separable from the variance account with the data at hand. What we can say descriptively is that adjusting for attempt likelihood did not improve held-out predictive accuracy in this sample, and that the selection-inheriting model remained the better forecaster of the kicks coaches actually chose to take.</p>
</section>
<section id="operational-implications" class="level2">
<h2 class="anchored" data-anchor-id="operational-implications">8.2 Operational Implications</h2>
<p>The operational implication is that selection-bias adjustment using these IPW methods does not work for predictive modeling. In the case of real-time make probability estimatation for in-game decision support, M1 is the recommended model. It has the strongest OOS predictive performance on both proper scoring rules, holds that advantage in both the pre-2020 and post-2020 halves of the sample (Section 5.4), and does not suffer from the weight-driven variance inflation of M3. For kicker evaluation, however, FGOE derived from M3-pop is the recommended metric because it adjusts for the context distribution under which each kicker was evaluated and corrects for the systematic selection bias in the attempt distribution. The baseline is constructed by zeroing the kicker term out of the fitted M3 rather than by refitting without it (Section 4.1).</p>
</section>
</section>
<section id="limitations" class="level1">
<h1>9. Limitations</h1>
<section id="estimand-and-the-relationship-to-causal-inference" class="level2">
<h2 class="anchored" data-anchor-id="estimand-and-the-relationship-to-causal-inference">9.1 Estimand and the Relationship to Causal Inference</h2>
<!-- RESERVED FOR M. SCHUCKERS (reviewer Main Comment 1): state the estimand we target
  (selection-reweighted, population-marginal success probability) vs. a causal
  counterfactual, and what a causal treatment would additionally require. -->
</section>
<section id="other-limitations" class="level2">
<h2 class="anchored" data-anchor-id="other-limitations">9.2 Other Limitations</h2>
<ol type="1">
<li><strong>Observational design</strong>: This study is observational, not causal. FGOE and M3-based evaluations describe how kickers performed relative to a selection-adjusted baseline, but cannot identify whether observed differences reflect true skill differences, variation in team context, or measurement noise.</li>
<li><strong>Pseudo-label sensitivity</strong>: M2 results depend on the PAT weight, non-attempt weight, propensity threshold, and distance threshold used to construct the augmented training set. The parameter grid evaluated in Section 5.2 shows fit degrading monotonically as the augmentation weight rises, and the exploratory classification of M2 reflects genuine sensitivity to these design choices.</li>
<li><strong>Sparse 60+ yard regime</strong>: The 60+ yard distance band contains only <span class="math inline">\(n = 77\)</span> in-sample observations, and only <span class="math inline">\(n = 15\)</span> in the held-out test set. The 22.1% Brier reduction for M3 at 60+ yards therefore carries high uncertainty and should be interpreted as directional evidence rather than a precise estimate.</li>
<li><strong>Additive weather assumption</strong>: The outcome models treat wind, temperature, and humidity as additive spline main effects on the logit. Physically, wind is likely to matter more on longer attempts, and an earlier specification modeled that through wind-by-distance interactions. Those terms are identified almost entirely from the sparse long-distance tail and were dropped (Section 4.1). The present results therefore assume that an interaction which plausibly exists is negligible in this sample.</li>
<li><strong>Single-league scope</strong>: The analysis is restricted to NFL data. The generalizability of the propensity model structure, the IPW weight distribution, and the FGOE evaluation framework to other levels of football (college, CFL) or other sports with similar coaching selection structures has not been tested.</li>
</ol>
</section>
</section>
<section id="conclusion" class="level1">
<h1>10. Conclusion</h1>
<p>NFL field goal modeling is a selection problem as well as a prediction problem. Coaches choose when to attempt kicks, and models trained only on observed attempts inherit the resulting sample bias. We tried two ways of correcting it. Rebuilding the training universe from imputed pseudo-labels (M2) did not work, and leaning harder on those labels made the fit worse rather than better, because the labels are wrong in a known direction that no choice of weight repairs. Applying inverse probability weighting (M3) reweights the observed sample toward the population of kickable situations without inventing any outcome, and in-sample this produces substantially better-calibrated predictions at long distance, achieving a 22.1% Brier reduction at 60+ yards versus the unweighted baseline. It does not improve out-of-sample global prediction, where the full GLMM (M1) remains the stronger model on both Brier score and log-loss, and remains so in both the pre-2020 and post-2020 eras. In practice, the recommended deployment is an M1-type model for in-game prediction and decision support, with M3 informing selection-bias diagnostics, and the M3-pop-based FGOE metric providing a principled, context-adjusted framework for kicker evaluation. Future work could explore doubly robust estimators as alternatives to pure IPW that may better balance bias correction with predictive stability.</p>
</section>
<section id="references" class="level1">
<h1>References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-nflfastr" class="csl-entry" role="listitem">
Carl, Sebastian, and Ben Baldwin. 2026. <em>nflfastR: Functions to Efficiently Access <span>NFL</span> Play by Play Data</em>. <a href="https://nflfastr.com/">https://nflfastr.com/</a>.
</div>
<div id="ref-long2019eval" class="csl-entry" role="listitem">
Long, Jacob A. 2019a. <em>A Better Way to Evaluate <span>NFL</span> Kickers</em>. <a href="https://jacob-long.com/post/evaluating-kickers/" class="uri">Https://jacob-long.com/post/evaluating-kickers/</a>.
</div>
<div id="ref-long2019methods" class="csl-entry" role="listitem">
Long, Jacob A. 2019b. <em>Building a Statistical Model for Field Goal Kicker Accuracy</em>. <a href="https://jacob-long.com/post/kickers-methods-notes/" class="uri">Https://jacob-long.com/post/kickers-methods-notes/</a>.
</div>
<div id="ref-osborne2017" class="csl-entry" role="listitem">
Osborne, Jason A., and Richard A. Levine. 2017. <span>“Shrinkage Estimation of <span>NFL</span> Field Goal Success Probabilities.”</span> <em>Journal of Sports Analytics</em> 3 (2): 129–46. <a href="https://doi.org/10.3233/JSA-16140">https://doi.org/10.3233/JSA-16140</a>.
</div>
<div id="ref-pasteur2014" class="csl-entry" role="listitem">
Pasteur, R. Drew, and Kyle Cunningham-Rhoads. 2014. <span>“An Expectation-Based Metric for <span>NFL</span> Field Goal Kickers.”</span> <em>Journal of Quantitative Analysis in Sports</em> 10 (1): 49–66. <a href="https://doi.org/10.1515/jqas-2013-0039">https://doi.org/10.1515/jqas-2013-0039</a>.
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>